defaults: &defaults
    working_directory: ~
    docker:
      - image: circleci/node:8.9.4-browsers
        environment:
                JETPACKHOST: JN
                NODE_ENV: test
                TARGET: JETPACK
                E2E_BRANCH: try/generic-circleci-container
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - run:
          name: Clone wp-e2e-tests repo
          command: |
                  git clone https://github.com/Automattic/wp-e2e-tests.git
                  cd wp-e2e-tests
                  git checkout origin/${E2E_BRANCH-master}
      - restore_cache:
          key: dependency-cache-{{ checksum "wp-e2e-tests/package.json" }}
      - run: cd wp-e2e-tests && npm install
      - save_cache:
          paths:
            - ./wp-e2e-tests/node_modules
          key: dependency-cache-{{ checksum "wp-e2e-tests/package.json" }}
      - run:
          name: Run Jetpack JN activation spec
          command: |
                  cd wp-e2e-tests
                  npm run decryptconfig
                  HEADLESS=1 ./node_modules/.bin/mocha scripts/jetpack/wp-jetpack-jn-activate.js
      - persist_to_workspace:
          root: wp-e2e-tests
          paths:
            - .
      - store_test_results:
          path: reports/
      - store_artifacts:
          path: reports/
      - store_artifacts:
          path: screenshots/
  test:
    <<: *defaults
    parallelism: 2
    steps:
      - attach_workspace:
          at: ~/wp-e2e-tests
      - run:
          name: Randomize spec execution order
          command: ./scripts/randomize.sh specs
      - run:
          name: Run e2e tests
          command: ./run.sh -R -j -p -x
      - store_test_results:
          path: reports/
      - store_artifacts:
          path: screenshots/
      - store_artifacts:
          path: reports/
workflows:
  version: 2
  build_test_destroy:
    jobs:
      - build:
          filters:
             branches:
                only:
                  - master
                  - /.*e2e.*/
      - test:
          requires:
            - build
