name: Jetpack Boost E2E Tests

on:
  pull_request:
    paths:
      - 'projects/plugins/boost/**'
  push:
    branches: [master]
    paths:
      - 'projects/plugins/boost/**'
concurrency:
  group: e2e-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-tests:
    name: "E2E tests"
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v2

      - name: Setup tools
        uses: ./.github/actions/tool-setup

      - name: Build Production Jetpack & Jetpack Boost
        run: |
          pnpm install
          pnpx jetpack build plugins/jetpack -v --production
          pnpx jetpack build plugins/boost -v --production

      - name: Environment set-up
        working-directory: projects/plugins/boost/tests/e2e
        env:
          CONFIG_KEY: ${{ secrets.E2E_CONFIG_KEY }}
        run: |
          pnpm install
          pnpm run test-decrypt-config
          pnpm run env-start
          pnpm run tunnel-on

      - name: Run tests
        working-directory: projects/plugins/boost/tests/e2e
        run: pnpm run test-e2e

      - name: Environment tear-down
        if: ${{ always() }}
        working-directory: projects/plugins/boost/tests/e2e
        continue-on-error: true
        run: |
          pnpm run tunnel-off
          pnpm run tunnel-write-logs

      - name: Upload test artifacts
        if: ${{ always() }}
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: test-output-boost
          path: projects/plugins/boost/tests/e2e/output

      - name: Send Slack notification
        if: ${{ failure() }}
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        working-directory: projects/plugins/boost/tests/e2e
        run: pnpm slack -- suite boost

      - uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}
        if: always()
      - name: Publish to Testspace
        working-directory: projects/plugins/boost/tests/e2e
        run: |
          testspace "[boost]output/reports/junit-*.xml"
        if: always()

  slack-notification:
    name: "Slack notification"
    runs-on: ubuntu-latest
    needs: e2e-tests
    env:
      CONFIG_KEY: ${{ secrets.E2E_CONFIG_KEY }}
      GITHUB_CONTEXT: ${{ toJson(github) }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup tools
        uses: ./.github/actions/tool-setup
        with:
          php: false

      - name: Send Slack notification
        working-directory: projects/plugins/boost/tests/e2e
        env:
          RESULT: ${{ needs.e2e-tests.result }}
        run: |
          pnpm install
          pnpm run test-decrypt-config
          pnpm slack -- status $RESULT --report boost

  test-reports:
    name: "Trigger test report workflow"
    runs-on: ubuntu-latest
    if: ${{ ! cancelled() }}
    needs: e2e-tests

    steps:
      - uses: actions/checkout@v2

      - name: Trigger test report workflow
        uses: ./.github/actions/test-report-dispatch
        with:
          token: ${{ secrets.E2E_TEST_REPORTS_TOKEN }}
          event_type: e2e
