name: Gardening
on:
  pull_request: # When a PR is opened, edited, updated, or a label is added.
    types: [opened, synchronize, labeled, edited]
  push:
    branches:
      - master # Every time a PR is merged to master.

jobs:
  triage:
    name: "Label PRs"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
    timeout-minutes: 1  # 2021-01-18: Successful runs seem to take a few seconds
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/actions/labeler.yml"
  # review-crew-afk:
  #   name: "Review check"
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'pull_request' && github.event.action == 'labeled' && github.event.label.name == '[Status] Needs Review'
  #   timeout-minutes: 1  # 2021-01-18: Successful runs probably take a few seconds
  #   steps:
  #     - name: Comment
  #       uses: actions/github-script@0.8.0
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         script: |
  #           github.issues.createComment({
  #             issue_number: context.issue.number,
  #             owner: context.repo.owner,
  #             repo: context.repo.repo,
  #             body: 'Howdy! The Jetpack team has disappeared for a few days to a secret island lair to concoct new ways to make Jetpack one hundred billion percent better. As a result, your Pull Request may not be reviewed right away. Do not worry, we will be back next week to look at your work! Thank you for your understanding.'
  #           })
  repo-gardening:
    name: "Manage labels and assignees"
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
    timeout-minutes: 1  # 2021-01-18: Successful runs seem to take a few seconds
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Building Action
        run: npm install
        working-directory: ./.github/actions/repo-gardening

      - name: "Run the action (assign, manage milestones, for issues and PRs)"
        uses: ./.github/actions/repo-gardening
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
